-- Deterministic demo postings for local review.

insert into postings (
  id,
  candidate_id,
  title,
  canonical_url,
  normalized_url,
  canonical_hash,
  sector,
  degree_level,
  opportunity_kind,
  organization_name,
  country,
  region,
  city,
  remote,
  tags,
  areas,
  description_text,
  application_url,
  deadline,
  source_refs,
  status,
  published_at,
  created_at,
  updated_at
)
values
  (
    '10000000-0000-0000-0000-000000000001',
    null,
    'PhD Position in Computational Biology',
    'https://example.edu/jobs/compbio-phd-001',
    'https://example.edu/jobs/compbio-phd-001',
    'demo-hash-001',
    'academia',
    'phd',
    'phd',
    'Northbridge University',
    'US',
    'CA',
    'San Diego',
    true,
    array['biology', 'ml'],
    array['Biology', 'Computer Science'],
    'Work on single-cell modeling and multimodal foundation models for discovery science.',
    'https://example.edu/apply/compbio-phd-001',
    now() + interval '45 days',
    '[{"kind":"seed","id":"demo-seed-001"}]'::jsonb,
    'active',
    now() - interval '2 hours',
    now() - interval '8 hours',
    now() - interval '2 hours'
  ),
  (
    '10000000-0000-0000-0000-000000000002',
    null,
    'Postdoc in Materials Informatics',
    'https://example.edu/jobs/materials-postdoc-002',
    'https://example.edu/jobs/materials-postdoc-002',
    'demo-hash-002',
    'academia',
    'postdoc',
    'postdoc',
    'Institute for Advanced Matter',
    'US',
    'MA',
    'Cambridge',
    false,
    array['materials', 'chemistry'],
    array['Chemistry & Materials Science'],
    'Develop active-learning pipelines for battery materials and autonomous synthesis loops.',
    'https://example.edu/apply/materials-postdoc-002',
    now() + interval '30 days',
    '[{"kind":"seed","id":"demo-seed-002"}]'::jsonb,
    'active',
    now() - interval '3 hours',
    now() - interval '9 hours',
    now() - interval '4 hours'
  ),
  (
    '10000000-0000-0000-0000-000000000003',
    null,
    'Research Engineer (NLP + Social Science)',
    'https://example.edu/jobs/nlp-social-003',
    'https://example.edu/jobs/nlp-social-003',
    'demo-hash-003',
    'industry',
    'masters',
    'full_time',
    'Civic Signals Lab',
    'UK',
    'England',
    'London',
    true,
    array['nlp', 'policy'],
    array['Political Science', 'Computer Science'],
    'Build text-analysis systems for public-interest research and multilingual civic datasets.',
    'https://example.edu/apply/nlp-social-003',
    now() + interval '21 days',
    '[{"kind":"seed","id":"demo-seed-003"}]'::jsonb,
    'active',
    now() - interval '4 hours',
    now() - interval '10 hours',
    now() - interval '6 hours'
  ),
  (
    '10000000-0000-0000-0000-000000000004',
    null,
    'Econometrics RA (Causal Inference)',
    'https://example.edu/jobs/econ-ra-004',
    'https://example.edu/jobs/econ-ra-004',
    'demo-hash-004',
    'academia',
    'bachelors',
    'contract',
    'Quant Methods Center',
    'US',
    'IL',
    'Chicago',
    false,
    array['economics', 'causal'],
    array['Economics'],
    'Support panel-data cleaning, experiment analysis, and reproducible policy evaluation reports.',
    'https://example.edu/apply/econ-ra-004',
    now() + interval '14 days',
    '[{"kind":"seed","id":"demo-seed-004"}]'::jsonb,
    'active',
    now() - interval '5 hours',
    now() - interval '11 hours',
    now() - interval '8 hours'
  ),
  (
    '10000000-0000-0000-0000-000000000005',
    null,
    'Education Data Scientist Fellowship',
    'https://example.edu/jobs/edu-data-005',
    'https://example.edu/jobs/edu-data-005',
    'demo-hash-005',
    'nonprofit',
    'masters',
    'fellowship',
    'Learning Futures Initiative',
    'CA',
    'ON',
    'Toronto',
    true,
    array['education', 'analytics'],
    array['Education'],
    'Analyze classroom intervention outcomes and help design teacher-facing decision support tools.',
    'https://example.edu/apply/edu-data-005',
    now() + interval '60 days',
    '[{"kind":"seed","id":"demo-seed-005"}]'::jsonb,
    'active',
    now() - interval '6 hours',
    now() - interval '12 hours',
    now() - interval '10 hours'
  ),
  (
    '10000000-0000-0000-0000-000000000006',
    null,
    'Math + Optimization Research Associate',
    'https://example.edu/jobs/math-opt-006',
    'https://example.edu/jobs/math-opt-006',
    'demo-hash-006',
    'industry',
    'bachelors',
    'full_time',
    'Applied Decisions Group',
    'DE',
    'Berlin',
    'Berlin',
    false,
    array['optimization', 'mathematics'],
    array['Mathematics'],
    'Prototype stochastic optimization workflows for operations planning and capacity forecasting.',
    'https://example.edu/apply/math-opt-006',
    now() + interval '25 days',
    '[{"kind":"seed","id":"demo-seed-006"}]'::jsonb,
    'active',
    now() - interval '7 hours',
    now() - interval '13 hours',
    now() - interval '12 hours'
  )
on conflict (canonical_hash) do update
set
  title = excluded.title,
  canonical_url = excluded.canonical_url,
  normalized_url = excluded.normalized_url,
  sector = excluded.sector,
  degree_level = excluded.degree_level,
  opportunity_kind = excluded.opportunity_kind,
  organization_name = excluded.organization_name,
  country = excluded.country,
  region = excluded.region,
  city = excluded.city,
  remote = excluded.remote,
  tags = excluded.tags,
  areas = excluded.areas,
  description_text = excluded.description_text,
  application_url = excluded.application_url,
  deadline = excluded.deadline,
  source_refs = excluded.source_refs,
  status = excluded.status,
  published_at = excluded.published_at,
  updated_at = excluded.updated_at;
